# NumPy Arrays - Complete Overview

This notebook covers: array creation, dimensions, shape, indexing, row/column selection, slicing, scalar arithmetic, vector math functions, element-wise arithmetic, comparison operators, broadcasting, aggregate functions, filtering, and random numbers.

See separate files for individual topics.

In [1]:
import sys

print(sys.executable)
print(sys.version)

/home/ravinder/drive/work_spaces/python/.venv/bin/python
3.14.7 (main, Aug 24 2026, 11:59:58) [GCC 15.2.0]


In [2]:
import numpy as np

print(np.__version__)

array = np.array([1, 2, 3, 4])
array = array * 2
print("array", array)
print("type(array)", type(array))  # <class 'numpy.ndarray'> # n-dimensional

2.5.2
array [2 4 6 8]
type(array) <class 'numpy.ndarray'>


## Dimensions (ndim)

In [3]:
# 0D array (scalar)
array = np.array('A')
print("array", array)
print("array.ndim", array.ndim)  # 0

array A
array.ndim 0


In [4]:
# 1D array
array = np.array([1, 2, 3, 4])
print("array", array)
print("array.ndim", array.ndim)  # 1
print("shape", array.shape)

array [1 2 3 4]
array.ndim 1
shape (4,)


In [5]:
# 2D array
array = np.array([
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
])
print("array", array)
print("array.ndim", array.ndim)  # 2
print("shape", array.shape)

array [['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
array.ndim 2
shape (3, 3)


In [6]:
# 3D array - shape (3,3,3)
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', 'a']],
])
print("array", array)
print("array.ndim", array.ndim)  # 3
print("array.shape", array.shape)  # (3,3,3) (depth, rows, columns)

array [[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' 'a']]]
array.ndim 3
array.shape (3, 3, 3)


In [7]:
# 3D array - shape (2,3,3)
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]
])
print("array", array)
print("array.ndim", array.ndim)  # 3
print("array.shape", array.shape)  # (2,3,3) (depth, rows, columns)
print("array[0][1][2]", array[0][1][2])
print("array[0,1,2]", array[0,1,2]) # same

array [[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]]
array.ndim 3
array.shape (2, 3, 3)
array[0][1][2] F
array[0,1,2] F


## Indexing 3D Arrays

In [8]:
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', 'a']]
])
print("array", array)
print("array[0][0][0]", array[0][0][0])  # index chaining
print("array[0,0,0]", array[0, 0, 0])  # depth, row, column
print("array[1,1,1]", array[1, 1, 1])
word = array[1, 1, 1] + array[1, 1, 2] + array[2, 0, 1]  # NOT
print("array[1,1,1] + array[1,1,2] + array[2,0,1]", word)

array [[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' 'a']]]
array[0][0][0] A
array[0,0,0] A
array[1,1,1] N
array[1,1,1] + array[1,1,2] + array[2,0,1] NOT


## Row Selection (arr[start:end:step])

In [9]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])
print("arr", arr)
print("arr[1]", arr[1])
print("arr[-1]", arr[-1])
print("arr[1:3]", arr[1:3])
print("arr[0:6:2]", arr[0:6:2])
print("arr[::2]", arr[::2])
print("arr[2]", arr[2])
print("all = arr[::1]", arr[::1])
print("all in reverse = arr[::-1]", arr[::-1]) # ***

arr [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
arr[1] [4 5 6]
arr[-1] [19 20 21]
arr[1:3] [[4 5 6]
 [7 8 9]]
arr[0:6:2] [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
arr[::2] [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
arr[2] [7 8 9]
all = arr[::1] [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
all in reverse = arr[::-1] [[19 20 21]
 [16 17 18]
 [13 14 15]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


## Column Selection (arr[row, column])

In [10]:
print("array", arr)
print("---------")
print("arr[1,2]", arr[1, 2])
print("all 2nd column elements arr[:,2]", arr[:, 2])
print("2nd last column arr[:,-2]", arr[:, -2])

array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
---------
arr[1,2] 6
all 2nd column elements arr[:,2] [ 3  6  9 12 15 18 21]
2nd last column arr[:,-2] [ 2  5  8 11 14 17 20]


## Slicing (arr[row-start:end:step, col-start:end:step])

In [11]:
print("array", arr)
print("---------")
print("arr[:,1:3] \n", arr[:, 1:3])
print("arr[:, 1:] \n", arr[:, 1:])
print("arr[:, ::2] \n", arr[:, ::2])
print("arr[:, 1::2] \n", arr[:, 1:2])
print("arr[:, ::-1] \n", arr[:, ::-1])
print("arr[0:2, 0:2] \n", arr[0:2, 0:2])
print("arr[0:2, 2:] \n", arr[0:2, 2:])

array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
---------
arr[:,1:3] 
 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]
 [17 18]
 [20 21]]
arr[:, 1:] 
 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]
 [17 18]
 [20 21]]
arr[:, ::2] 
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]
 [13 15]
 [16 18]
 [19 21]]
arr[:, 1::2] 
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]
 [20]]
arr[:, ::-1] 
 [[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]
 [15 14 13]
 [18 17 16]
 [21 20 19]]
arr[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr[0:2, 2:] 
 [[3]
 [6]]


## Scalar Arithmetic

In [12]:
array = np.array([1, 2, 3, 4, 5])
print(array)
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array // 2) # does round up
print(array % 2)
print(array ** 2)

[1 2 3 4 5]
[2 3 4 5 6]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.25 0.5  0.75 1.   1.25]
[0 1 1 2 2]
[1 0 1 0 1]
[ 1  4  9 16 25]


## Vector Math Functions

In [13]:
array = np.array([1, 2, 3, 4, 5])
print(np.square(array))
print(np.sqrt(array))
array = np.array([1.03, 1.41421356, 1.73205081, 2.414, 4.23606798])
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))
print(np.pi)
array = np.array([1, 2, 3, 4, 5])
print(np.power(array, 2))

# Exercise: calculate area of circles
radii = np.array([1, 2, 3, 4])
print(np.pi * radii ** 2)

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1. 1. 2. 2. 4.]
[2. 2. 2. 3. 5.]
[1. 1. 1. 2. 4.]
3.141592653589793
[ 1  4  9 16 25]
[ 3.14159265 12.56637061 28.27433388 50.26548246]


## Element-wise Arithmetic

In [14]:
array1 = np.array([1, 2, 3])
arra2 = np.array([4, 5, 6])
print(array1 + arra2)
print(array1 - arra2)
print(array1 * arra2)
print(array1 / arra2)
print(array1 ** arra2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


## Comparison Operators

In [15]:
scores = np.array([56, 36, 23, 40])
print(scores > 36)
print(scores <= 35)
print(scores == 40)
scores[scores < 35] = 0 # replace scores below 35 with 0
print("replaced=",scores)

[ True False False  True]
[False False  True False]
[False False False  True]
replaced= [56 36  0 40]


## Broadcasting ( Expanding )

Rule: Arrays should have the same dimension or one of them should have size 1.

In [16]:
# (1,4) * (4,1) = (4,4)
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[5], [6], [7], [8]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 4)
(4, 1)
[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [17]:
# (2,4) * (4,1) - ERROR: incompatible shapes
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array2 = np.array([[5], [6], [7], [8]])
print(array1.shape)
print(array2.shape)
# print(array1 * array2)  # error

(2, 4)
(4, 1)


### Imprtant Broadcasting

In [18]:
# (4,4) * (4,1) = works!
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array2 = np.array([[5], [6], [7], [8]])
print(array1 * array2)

[[  5  10  15  20]
 [ 30  36  42  48]
 [ 63  70  77  84]
 [104 112 120 128]]


```mermaid
flowchart LR
    A["array1<br/>(4,4)<br/><br/>1  2  3  4<br/>5  6  7  8<br/>9 10 11 12<br/>13 14 15 16"]
    
    B["array2<br/>(4,1)<br/><br/>5<br/>6<br/>7<br/>8"]
    
    C["Broadcast<br/>(4,1) → (4,4)<br/><br/>5 5 5 5<br/>6 6 6 6<br/>7 7 7 7<br/>8 8 8 8"]
    
    D["Element-wise multiplication<br/><br/>5  10  15  20<br/>30 36  42  48<br/>63 70  77  84<br/>104 112 120 128"]

    A --> D
    B --> C
    C --> D
```

In [19]:
# (4,4) * (4,2) - NOT possible
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array2 = np.array([[5, 1], [6, 2], [7, 3], [8, 2]])
# print(array1 * array2)  # not possible
print(array1, array2, "(array1 * array2)  # not possible")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] [[5 1]
 [6 2]
 [7 3]
 [8 2]] (array1 * array2)  # not possible


In [20]:
# Multiplication tables: (1,10) * (10,1)
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


```mermaid
flowchart TD
    A["array1<br/>(1,10)<br/><br/>1 2 3 4 5 6 7 8 9 10"]
    
    B["array2<br/>(10,1)<br/><br/>1<br/>2<br/>3<br/>4<br/>...<br/>10"]
    
    C["Broadcasting<br/><br/>(1,10) → (10,10)<br/>(10,1) → (10,10)"]
    
    D["array1 after broadcasting<br/>(10,10)<br/><br/>1 2 3 4 5 6 7 8 9 10<br/>1 2 3 4 5 6 7 8 9 10<br/>1 2 3 4 5 6 7 8 9 10<br/>...<br/>1 2 3 4 5 6 7 8 9 10"]
    
    E["array2 after broadcasting<br/>(10,10)<br/><br/>1 1 1 1 1 1 1 1 1 1<br/>2 2 2 2 2 2 2 2 2 2<br/>3 3 3 3 3 3 3 3 3 3<br/>...<br/>10 10 10 10 10 10 10 10 10 10"]
    
    F["Element-wise multiplication<br/><br/>array1 × array2"]
    
    G["10 × 10 multiplication table"]
    
    A --> C
    B --> C
    
    C --> D
    C --> E
    
    D --> F
    E --> F
    
    F --> G
```

## Aggregate Functions

In [21]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.sum(array))
print(np.max(array))
print(np.min(array))
print(np.argmin(array)) # Give me the index/position of the min value.
print(np.argmax(array)) # Give me the index/position of the max value.
print(np.mean(array)) # mean = average
print(np.std(array)) # std = standard deviation.
print(np.var(array)) # variance = standard deviation² # just to make std positive by squaring
print(np.sum(array, axis=1))

55
10
1
0
9
5.5
2.8722813232690143
8.25
[15 40]


### Standerd Deviation
> Standard deviation (SD) tells us how much the values in a dataset are spread out from their mean (average).

[Read STD](../_maths/variance_standerd_deviation.md)

### Axis

axis=0 -> row-wise  
axis=1 -> column-wise  

```text
             axis=1 →
        ┌───────────────
axis=0  │ 1  2  3  4  5
  ↓     │ 6  7  8  9 10
```

## Filtering

In [22]:
ages = np.array([[10, 19, 18, 28, 54, 65, 33], [1, 17, 27, 34, 87, 69, 77]])
print("ages", ages)
teenagers = ages[ages < 18]
print("teenagers",teenagers)
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)
good_people = ages[(ages < 18) | (ages > 65)]
print(good_people)
seniors = ages[ages > 65]
print(seniors)
evens = ages[ages % 2 == 0]
print(evens)
adults = np.where(ages > 18, ages, 0) # if false...replace with zero
print("adults",adults)

ages [[10 19 18 28 54 65 33]
 [ 1 17 27 34 87 69 77]]
teenagers [10  1 17]
[19 18 28 54 33 27 34]
[10  1 17 87 69 77]
[87 69 77]
[10 18 28 54 34]
adults [[ 0 19  0 28 54 65 33]
 [ 0  0 27 34 87 69 77]]


## Random Numbers

In [23]:
# Random integer generation
rng = np.random.default_rng()
print(rng.integers(low=1, high=100))
print(rng.integers(low=1, high=100, size=3))
print(rng.integers(low=1, high=100, size=(3, 2))) # array 3*2

99
[21 97 69]
[[10 71]
 [16  6]
 [ 6 46]]


In [24]:
# Seed for reproducible results ( same random numbers )
rng = np.random.default_rng(seed=1) # default_rng = default - random number generator
print(rng.integers(low=1, high=100))
print(rng.integers(low=1, high=100, size=3))
print(rng.integers(low=1, high=100, size=(3, 2)))

47
[51 75 95]
[[ 4 15]
 [82 94]
 [25 31]]


In [25]:
# Uniform distribution
print(np.random.uniform())
print(np.random.uniform(low=-1, high=1))
print("size=3",np.random.uniform(low=-1, high=1, size=3))
print("size=(3,2)",np.random.uniform(low=-1, high=1, size=(3, 2)))

np.random.seed(seed=1)
print("seed",np.random.uniform(low=-1, high=1, size=(3, 2)))

0.8034249820863201
-0.053302096873831806
size=3 [-0.53381301 -0.03123264 -0.88568057]
size=(3,2) [[-0.45492245 -0.99479565]
 [ 0.4364849   0.32759334]
 [ 0.91650258  0.06833225]]
seed [[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


### Uniform distribution

> np.random.uniform(low=-1, high=1, size=1000)
generates 1000 random values between -1 and 1.

Conceptually:

```text
Probability
    │
    │  ─────────────────
    │  │               │
    │  │   Uniform     │
    │  │ Distribution  │
    │  │               │
    └──┴───────────────┴──────→ Value
      -1               1
```

In [26]:
# Shuffle and choice
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)
fruits = np.array(["apple", "banana", "cherry", "grape", "mango"])
fruit = rng.choice(fruits)
print("choice fruit",fruit)
three_fruits = rng.choice(fruits, size=3)
print(three_fruits)
many_fruits = rng.choice(fruits, size=(3, 3))
print(many_fruits)

[2 5 1 3 4]
choice fruit grape
['apple' 'grape' 'cherry']
[['cherry' 'apple' 'apple']
 ['banana' 'apple' 'banana']
 ['banana' 'mango' 'apple']]
