# Array Indexing & Slicing

## 3D Array Indexing

In [1]:
import numpy as np

array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', 'a']]
])
print("array", array)
print("array[0][0][0]", array[0][0][0])  # index chaining
print("array[0,0,0]", array[0, 0, 0])  # depth, row, column
print("array[1,1,1]", array[1, 1, 1])
word = array[1, 1, 1] + array[1, 1, 2] + array[2, 0, 1]  # NOT
print("array[1,1,1] + array[1,1,2] + array[2,0,1]", word)

array [[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' 'a']]]
array[0][0][0] A
array[0,0,0] A
array[1,1,1] N
array[1,1,1] + array[1,1,2] + array[2,0,1] NOT


## Row Selection (arr[start:end:step])

In [2]:
arr = np.array([
    [1, 2, 3], [4, 5, 6], [7, 8, 9],
    [10, 11, 12], [13, 14, 15], [16, 17, 18]
])
print("arr", arr)
print("arr[1]", arr[1])
print("arr[-1]", arr[-1])
print("arr[1:2]", arr[1:2])
print("arr[1:5:2]", arr[1:5:2])
print("arr[::2]", arr[::2])
print("arr[2]", arr[2])
print("all = arr[::1]", arr[::1])
print("all in reverse = arr[::-1]", arr[::-1])

arr [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
arr[1] [4 5 6]
arr[-1] [16 17 18]
arr[1:2] [[4 5 6]]
arr[1:5:2] [[ 4  5  6]
 [10 11 12]]
arr[::2] [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
arr[2] [7 8 9]
all = arr[::1] [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
all in reverse = arr[::-1] [[16 17 18]
 [13 14 15]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


## Column Selection (arr[row, column])

In [3]:
print("arr[1,2]", arr[1, 2])
print("all 2nd column elements arr[:,2]", arr[:, 2])
print("2nd last column arr[:,-2]", arr[:, -2])

arr[1,2] 6
all 2nd column elements arr[:,2] [ 3  6  9 12 15 18]
2nd last column arr[:,-2] [ 2  5  8 11 14 17]


## 2D Slicing (arr[row-start:end:step, col-start:end:step])

In [4]:
print("arr[:,1:3]", arr[:, 1:3])
print("arr[:, 1:]", arr[:, 1:])
print("arr[:, ::2]", arr[:, ::2])
print("arr[:, 1::2]", arr[:, 1:2])
print("arr[:, ::-1]", arr[:, ::-1])
print("arr[0:2, 0:2]", arr[0:2, 0:2])
print("arr[0:2, 2:]", arr[0:2, 2:])

arr[:,1:3] [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]
 [17 18]]
arr[:, 1:] [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]
 [17 18]]
arr[:, ::2] [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]
 [13 15]
 [16 18]]
arr[:, 1::2] [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
arr[:, ::-1] [[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]
 [15 14 13]
 [18 17 16]]
arr[0:2, 0:2] [[1 2]
 [4 5]]
arr[0:2, 2:] [[3]
 [6]]
