# Array Math Operations

## Scalar Arithmetic (applied to each element)

In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(array)
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array // 2)
print(array % 2)
print(array ** 2)

[1 2 3 4 5]
[2 3 4 5 6]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.25 0.5  0.75 1.   1.25]
[0 1 1 2 2]
[1 0 1 0 1]
[ 1  4  9 16 25]


## Vector Math Functions

In [2]:
array = np.array([1, 2, 3, 4, 5])
print(np.square(array))
print(np.sqrt(array))
array = np.array([1.03, 1.41421356, 1.73205081, 2.414, 4.23606798])
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))
print(np.pi)
array = np.array([1, 2, 3, 4, 5])
print(np.power(array, 2))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1. 1. 2. 2. 4.]
[2. 2. 2. 3. 5.]
[1. 1. 1. 2. 4.]
3.141592653589793
[ 1  4  9 16 25]


## Exercise: Circle Areas

In [3]:
radii = np.array([1, 2, 3, 4])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


## Element-wise Arithmetic

In [4]:
array1 = np.array([1, 2, 3])
arra2 = np.array([4, 5, 6])
print(array1 + arra2)
print(array1 - arra2)
print(array1 * arra2)
print(array1 / arra2)
print(array1 ** arra2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


## Comparison Operators

In [5]:
scores = np.array([56, 36, 23, 40])
print(scores > 36)
print(scores <= 35)
print(scores == 40)
scores[scores < 35] = 0
print(scores)

[ True False False  True]
[False False  True False]
[False False False  True]
[56 36  0 40]
