# Array Broadcasting

**Rule:** For broadcasting to work, arrays should have the same dimension or one of them should have size 1 in that dimension.

## Basic Broadcasting: (1,4) * (4,1)

In [1]:
import numpy as np

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[5], [6], [7], [8]])
print(array1.shape)  # (1,4)
print(array2.shape)  # (4,1)
print(array1 * array2)

(1, 4)
(4, 1)
[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


## Incompatible Shapes: (2,4) * (4,1)

In [2]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array2 = np.array([[5], [6], [7], [8]])
print(array1.shape)  # (2,4)
print(array2.shape)  # (4,1)
# print(array1 * array2)  # error - rows don't match (2 vs 4) and neither is 1

(2, 4)
(4, 1)


## Compatible: (4,4) * (4,1)

In [3]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array2 = np.array([[5], [6], [7], [8]])
print(array1 * array2)

[[  5  10  15  20]
 [ 30  36  42  48]
 [ 63  70  77  84]
 [104 112 120 128]]


## Incompatible: (4,4) * (4,2)

In [4]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array2 = np.array([[5, 1], [6, 2], [7, 3], [8, 2]])
# print(array1 * array2)  # not possible - columns 4 vs 2, neither is 1
print(array1, array2, "(array1 * array2)  # not possible")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] [[5 1]
 [6 2]
 [7 3]
 [8 2]] (array1 * array2)  # not possible


## Multiplication Table: (1,10) * (10,1)

In [5]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
