# Filtering Arrays

In [1]:
import numpy as np

ages = np.array([[10, 19, 18, 28, 54, 65, 33], [1, 17, 27, 34, 87, 69, 77]])
print("ages", ages)

ages [[10 19 18 28 54 65 33]
 [ 1 17 27 34 87 69 77]]


## Boolean Indexing

In [2]:
# Teenagers (< 18)
teenagers = ages[ages < 18]
print(teenagers)

[10  1 17]


In [3]:
# Adults (>= 18 and < 65)
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

[19 18 28 54 33 27 34]


In [4]:
# Good people (< 18 or > 65)
good_people = ages[(ages < 18) | (ages > 65)]
print(good_people)

[10  1 17 87 69 77]


In [5]:
# Seniors (> 65)
seniors = ages[ages > 65]
print(seniors)

[87 69 77]


In [6]:
# Even ages (% 2 == 0)
evens = ages[ages % 2 == 0]
print(evens)

[10 18 28 54 34]


## np.where() - Preserves Dimensions

Unlike boolean indexing which flattens the result, `np.where()` preserves the original array shape.

In [7]:
adults = np.where(ages > 18, ages, 0)
print(adults)

[[ 0 19  0 28 54 65 33]
 [ 0  0 27 34 87 69 77]]
