# Random Numbers in NumPy

## Random Integer Generation (default_rng)

In [1]:
import numpy as np

rng = np.random.default_rng()
print(rng.integers(low=1, high=100))
print(rng.integers(low=1, high=100, size=3))
print(rng.integers(low=1, high=100, size=(3, 2)))

24
[79 99 61]
[[38 37]
 [80 42]
 [ 4 33]]


## Seed (Reproducible Results)

In [2]:
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=100))
print(rng.integers(low=1, high=100, size=3))
print(rng.integers(low=1, high=100, size=(3, 2)))

47
[51 75 95]
[[ 4 15]
 [82 94]
 [25 31]]


## Uniform Distribution (old style)

In [3]:
print(np.random.uniform())
print(np.random.uniform(low=-1, high=1))
print(np.random.uniform(low=-1, high=1, size=3))
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

0.006466788548814439
0.9609111993218715
[0.28288325 0.95568629 0.65468688]
[[-0.05590124 -0.82215386]
 [ 0.66153526 -0.63664826]
 [ 0.69044396  0.12226841]]


## Uniform with Seed

In [4]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


## Shuffle & Choice

In [5]:
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

fruits = np.array(["apple", "banana", "cherry", "grape", "mango"])
fruit = rng.choice(fruits)
print(fruit)
three_fruits = rng.choice(fruits, size=3)
print(three_fruits)
many_fruits = rng.choice(fruits, size=(3, 3))
print(many_fruits)
too_many_fruits = rng.choice(fruits, size=(3, 3, 3))
print(too_many_fruits)

[3 2 5 4 1]
mango
['grape' 'cherry' 'apple']
[['cherry' 'apple' 'cherry']
 ['cherry' 'grape' 'grape']
 ['cherry' 'mango' 'cherry']]
[[['mango' 'cherry' 'mango']
  ['mango' 'mango' 'grape']
  ['grape' 'grape' 'grape']]

 [['mango' 'grape' 'mango']
  ['grape' 'apple' 'mango']
  ['banana' 'cherry' 'banana']]

 [['mango' 'apple' 'banana']
  ['banana' 'mango' 'apple']
  ['mango' 'mango' 'apple']]]
