### Load in NumPy (remember to pip install numpy first)

In [4]:
import numpy as np

### The Basics

In [5]:
a = np.array([1,2,3], dtype='int32') # a = np.array([1,2,3])
# a = np.array([1,2,3], dtype='int16')


print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [10]:
# Get Size
a.itemsize

4

In [11]:
# Get total size
a.nbytes

12

In [12]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 5]
# a[1, -2]

np.int64(13)

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [17]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [18]:
a[1,5] = 20

a[:,2] = [1,2]
# a[:,2] = 5 # sets all values to 5
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [21]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]] # error
# b[:,1,:] = [[9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [22]:
np.random.random_sample(a.shape)

array([[0.43832644, 0.22984184, 0.90972842, 0.29399247, 0.12966767,
        0.4424514 , 0.43445564],
       [0.20729211, 0.43001884, 0.41069503, 0.87494906, 0.52340021,
        0.53849677, 0.18952679]])

In [73]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [98]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]


### Mathematics

In [111]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([5, 6, 7, 8])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [134]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.min(stats)

1

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [25]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [32]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata) # floats
print("-----")
filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
-----
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [36]:
results = filedata[filedata > 50] # filedata > 50 returns indices
print(results)
print("=====")
fixed = filedata[[1,2],[2,2]]
print(fixed)
np.any(filedata > 50, axis=0)

[196  75 766  75  55 999  78  76  88]
=====
[12 33]


array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [30]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,8]]

array([2, 3, 9])

In [42]:
arr = np.array([
    [1, 2, 3, 4,  5],
    [6, 7, 8, 9, 10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])
res = arr[2:4, 0:2]
print(res)
res = arr[[0,1,2,3],[1,2,3,4]]
print(res)
res = arr[[0,4,5],3:]
print(res)

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
